from .role import Role
import random


class System(Role):
    def __init__(self, tools):
        self.name = "System"
        self.template = "As the System, you can parse JSON blobs and store tools, as well as execute them when required."
        self.conversation_history = {}
        self.temperature = 0.1 * random.randint(1, 9)
        self.max_tokens = random.randint(250, 400)
        self.tools = tools

    def append_tool(self, tool):
        self.tools.append(tool)

    def execute_tool(self, tool_name, args):
        if tool_name in self.tools:
            tool = self.tools[tool_name]
            code = tool["code"]
            exec(code, globals(), args)
            return args.get("response", "No response generated by tool.")
        else:
            return f"Error: Tool '{tool_name}' not found."

    def interact(self, prompt):
        print(colored(f"\n---\n// {self.name}\n{prompt}\n---\n", "grey"))

        if prompt is not None and prompt.startswith("{"):
            try:
                instruction = json.loads(prompt)

                if "code" in instruction:
                    self.append_tool(instruction)

                    return f"Stored tool '{instruction['function']['name']}' with args {instruction['function']['parameters']['properties'].keys()}."
                elif "exec" in instruction:
                    code_name = instruction["exec"]
                    args = instruction["args"]
                    self.execute_tool(code_name, args)
                    return f"Executed tool '{code_name}' with args {args}."
            except json.JSONDecodeError as e:
                return f"Error: {e}"
            except Exception as e:
                return f"Error: {e}"
        else:
            return "Error: no JSON submitted"
